error.host=Kein Computername definiert
logpath.meta = C:\\Users\\TSZ\\Daten\\Java\\Applications\\application\\logs
logpath.privat = C:\\Users\\Privat\\Daten\\Java\\Applications\\application\\logs
logpath.schmi = C:\\Users\\schmi\\Daten\\Java\\Applications\\application\\logs
logpath.test = C:\\Users\\test\\Daten\\Java\\Applications\\application\\logs
meta.pc=22H0566
privat.pc = DESKTOP-3NCAR95
schmi.pc = DESKTOP-Q6O0UGB
test.pc = DESKTOP-LERLCJ6